### ISSUE TITLE
dim with me not dimming with me

### ISSUE THREAD

**Issue by jgallen23** [twack/smarthings-apps#2]
I've got a GE Dimmer Switch and some GE link bulbs and I've set up the GE Dimmer switch as the master and the GE Link bulbs as dimmers.  When I change the master dimmer from the app, it doesn't change anything with the ge link bulbs.  Any way for me to debug this?  I've followed the logs, and it shows the master dimmer change, but nothing else.

**Comment by twack** [comment]
Hello,
The original published GE Link device file did not use the "setLevel" command whihc Dim-With-Me subscribes to. Update the Link bulb device type with this: https://github.com/twack/smartthings-devices/blob/master/Wackware-GE-Link-Bulb.groovy and it should work.

**Comment by jgallen23** [comment]
@twack the GE link bulb is not my master device.  The GE Dimmer Switch is.

**Comment by jgallen23** [comment]
bump.  @twack any ideas?

**Comment by twack** [comment]
Ah yes the dreaded GE Dimmer "not reporting dim level" issue. GE did not license the "immediate reporting of level setting" from I believe Leviton. You'll find many forum entries on this. The GE Dimmer eventually reports (maybe 5 minutes later) and then Dim With Me will take action.

**Comment by jgallen23** [comment]
Ahh. Bummer. Thanks for the info
